'------------------------------------------------------------------------------
' <auto-generated>
'     Bu kod araç tarafından oluşturuldu.
'     Çalışma Zamanı Sürümü:4.0.30319.42000
'
'     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
'     kod yeniden oluşturulursa kaybolur.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System

Namespace Themer.Sample.Properties


    ''' <summary>
    '''   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    ''' </summary>
    ' Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    ' sınıfı tarafından otomatik olarak oluşturuldu.
    ' Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    ' komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class Resources

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
        End Sub

        ''' <summary>
        '''   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Themer.Sample.Properties.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        '''   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set(ByVal value As Global.System.Globalization.CultureInfo)
                resourceCulture = value
            End Set
        End Property

        ''' <summary>
        '''   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_air As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_air", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_blur As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_blur", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_github_1 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_github_1", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_info_3 As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_info_3", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_restore As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_restore", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        ''' </summary>
        Friend Shared ReadOnly Property icons8_visualy_impaired As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_visualy_impaired", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
